import { fal } from "@ai-sdk/fal";
import { google } from "@ai-sdk/google";
import {
  FILE_UPLOAD_FEATURE,
  IMAGE_GENERATION_FEATURE,
  PDF_PROCESSING_FEATURE,
  REASONING_FEATURE,
  REASONING_FEATURE_ALWAYS,
  REASONING_FEATURE_DISABLED,
  TOOL_CALLING_FEATURE,
} from "../features";

export const GOOGLE_MODELS = [
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    retired: true,
    description: `Google's fast multimodal model with native tool use.\nExcels at general tasks, web search, and real-time applications.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.0-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    retired: true,
    description:
      "Most cost-efficient Gemini model with fast responses.\nIdeal for high-volume, latency-sensitive applications.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.0-flash-lite"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description: `Google's flagship light model.\nExcels at agentic use cases and large-scale processing.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-thinking",
    name: "Gemini 2.5 Flash",
    subName: "Thinking",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Gemini flagship light model with reasoning capabilities enabled.\nFeatures visible thought process for complex problem-solving with thinking.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Most cost-efficient and fastest model with lowest latency.\nIdeal for high-volume classification and summarization tasks.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash-lite"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-flash-lite-thinking",
    name: "Gemini 2.5 Flash Lite",
    subName: "Thinking",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Flash Lite with adjustable thinking budget for reasoning.\nCombines cost-efficiency with controllable thinking capabilities.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    api_sdk: google("gemini-2.5-flash-lite"),
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description: `Google's state-of-the-art model leading math and science benchmarks.\nExcels at creating web apps and agentic code applications.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-2.5-pro"),
  },
  {
    id: "imagen-4",
    name: "Imagen 4",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description: `Google's flagship text-to-image model with superior text rendering.\nCreates photorealistic images with precise instruction following.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: fal.image("fal-ai/imagen4/preview/fast"),
  },
  {
    id: "imagen-4-ultra",
    name: "Imagen 4 Ultra",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description:
      "Ultra-precise image generation model with enhanced prompt adherence.\nDesigned for professional applications requiring exact specifications.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: fal.image("fal-ai/imagen4/preview/ultra"),
  },
  {
    id: "nano-banana",
    name: "Nano Banana",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description:
      "Google's fast image generation model based on Gemini 2.5 Flash.\nOptimized for speed and efficiency with high-volume, low-latency tasks.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: fal.image("fal-ai/gemini-25-flash-image"),
  },
  {
    id: "nano-banana-2",
    name: "Nano Banana 2",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description:
      "Google's latest high-efficiency image model based on Gemini 3.1 Flash Image.\nDelivers faster generation and editing with strong quality for high-volume workflows.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: google.image("gemini-3.1-flash-image"),
  },
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description:
      "Google's state-of-the-art image generation model based on Gemini 3 Pro.\nFeatures high-fidelity text rendering, 4K output, and advanced reasoning for complex compositions.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: google.image("gemini-3-pro-image"),
  },
  {
    id: "gemini-3.1-flash-lite-image",
    name: "Nano Banana 2 Lite",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description:
      "Google's lowest-cost Gemini 3.1 image model.\nOptimized for fast, high-volume generation and editing.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: google.image("gemini-3.1-flash-lite-image"),
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    description:
      "Google's latest fast multimodal model for agentic work.\nSupports tools, adaptive reasoning, files, and long context.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_ALWAYS,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-3.5-flash"),
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    description:
      "Google's efficient stable Gemini 3.1 model.\nSupports multimodal files, tools, reasoning, and high-volume workloads.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_ALWAYS,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-3.1-flash-lite"),
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: true,
    description:
      "Google's most advanced reasoning model capable of solving complex problems.\nFeatures improved agentic capabilities, better thinking, and a 1M token context window.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_ALWAYS,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-3.1-pro-preview"),
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Frontier intelligence built for speed at a fraction of the cost.\nExcels at agentic coding with upgraded visual and spatial reasoning.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-3-flash-preview"),
  },
  {
    id: "gemini-3-flash-preview-thinking",
    name: "Gemini 3 Flash",
    subName: "Thinking",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Gemini 3 Flash with reasoning capabilities enabled.\nDeep thinking for complex problem-solving and agentic tasks.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-3-flash-preview"),
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    retired: true,
    description:
      "Google's fastest Gemini 3.1 preview model for high-volume, low-latency tasks.\nOptimized for cost-efficient multimodal processing and lightweight agentic workflows.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-3.1-flash-lite-preview"),
  },
  {
    id: "gemini-3.1-flash-lite-preview-thinking",
    name: "Gemini 3.1 Flash Lite",
    subName: "Thinking",
    provider: "gemini",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    retired: true,
    description:
      "Gemini 3.1 Flash Lite Preview with reasoning enabled.\nAdds deeper thinking for multi-step tasks while keeping low latency and cost efficiency.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: google("gemini-3.1-flash-lite-preview"),
  },
];
