import {
  FILE_UPLOAD_FEATURE,
  PDF_PROCESSING_FEATURE,
  REASONING_FEATURE_FIXED,
  REASONING_FEATURE_MAX,
  REASONING_FEATURE_TOGGLE,
  TOOL_CALLING_FEATURE,
} from "../features";
import { openrouter } from "../openrouter";

export const MOONSHOT_MODELS = [
  {
    id: "moonshotai/kimi-k3",
    name: "Kimi K3",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: true,
    description:
      "Moonshot AI's multimodal reasoning flagship.\nBuilt for complex coding, knowledge work, and long-horizon agentic workflows.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      TOOL_CALLING_FEATURE,
      REASONING_FEATURE_MAX,
    ],
    api_sdk: openrouter("moonshotai/kimi-k3"),
  },
  {
    id: "moonshotai/kimi-k2.6",
    name: "Kimi K2.6",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Moonshot AI's multimodal general-purpose model.\nSupports optional reasoning, tools, and agentic coding workflows.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      TOOL_CALLING_FEATURE,
      REASONING_FEATURE_TOGGLE,
    ],
    api_sdk: openrouter("moonshotai/kimi-k2.6"),
  },
  {
    id: "moonshotai/kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: false,
    description:
      "Moonshot AI's always-thinking coding model.\nBuilt for long-horizon software engineering and tool-driven tasks.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [TOOL_CALLING_FEATURE, REASONING_FEATURE_FIXED],
    api_sdk: openrouter("moonshotai/kimi-k2.7-code"),
  },
  {
    id: "moonshotai/kimi-k2-0711",
    name: "Kimi K2",
    subName: "0711",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description: "Moonshot AI's original Kimi K2 model.\nSupports agentic tool use.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [TOOL_CALLING_FEATURE],
    api_sdk: openrouter("moonshotai/kimi-k2:nitro"),
  },
  {
    id: "moonshotai/kimi-k2-0905",
    name: "Kimi K2",
    subName: "0905",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Moonshot AI's September 2025 Kimi K2 update.\nImproved agentic coding and frontend work.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [TOOL_CALLING_FEATURE],
    api_sdk: openrouter("moonshotai/kimi-k2-0905:nitro"),
  },
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description: "Moonshot AI's previous multimodal flagship.\nStrong coding and agentic tool use.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [FILE_UPLOAD_FEATURE, PDF_PROCESSING_FEATURE, TOOL_CALLING_FEATURE],
    api_sdk: openrouter("moonshotai/kimi-k2.5"),
  },
  {
    id: "moonshotai/kimi-k2.5:reasoning",
    name: "Kimi K2.5",
    subName: "Thinking",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Moonshot AI's previous reasoning flagship.\nOptimized for complex multi-step workflows.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      TOOL_CALLING_FEATURE,
      REASONING_FEATURE_TOGGLE,
    ],
    api_sdk: openrouter("moonshotai/kimi-k2.5"),
  },
  {
    id: "moonshotai/kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "openrouter",
    displayProvider: "moonshotai",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description: "Moonshot AI's previous always-thinking model.\nDesigned for complex workflows.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [TOOL_CALLING_FEATURE, REASONING_FEATURE_FIXED],
    api_sdk: openrouter("moonshotai/kimi-k2-thinking"),
  },
];
