import { gateway } from "@ai-sdk/gateway";
import { openai } from "@ai-sdk/openai";
import {
  FILE_UPLOAD_FEATURE,
  IMAGE_GENERATION_FEATURE,
  PDF_PROCESSING_FEATURE,
  REASONING_FEATURE,
  REASONING_FEATURE_DISABLED,
  TOOL_CALLING_FEATURE,
} from "../features";
// import { openrouter } from '../openrouter';

export const OPENAI_MODELS = [
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    description:
      "OpenAI's latest flagship model for professional work.\nStronger on reasoning, coding, tool use, and long-running workflows.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.4"),
  },
  {
    id: "gpt-5.4-pro",
    name: "GPT-5.4 Pro",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description:
      "Maximum-performance GPT-5.4 variant for the hardest reasoning and agentic tasks.\nBest reserved for expert analysis and long-horizon workflows.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.4-pro"),
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description:
      "OpenAI's strongest mini model yet for coding, computer use, and subagents.\nBest for high-volume GPT-5.4-class workflows that still need reasoning and tools.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.4-mini"),
  },
  {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description:
      "OpenAI's cheapest GPT-5.4-class model for simple high-volume tasks.\nStrong fit for classification, extraction, ranking, and lightweight subagents.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.4-nano"),
  },
  {
    id: "gpt-5.3-instant",
    name: "GPT-5.3 Instant",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    description:
      "Newest ultra-fast GPT-5.3 instant model tuned for low-latency interactions.\nBest for quick responses, live chat, and tool-augmented workflows.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.3-chat-latest"),
  },
  {
    id: "gpt-5.2",
    name: "GPT-5.2",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description:
      "Previous-generation GPT-5 reasoning model.\nStill strong for logic, coding, and multi-step reasoning workloads.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.2"),
  },
  {
    id: "gpt-5.2-pro",
    name: "GPT-5.2 Pro",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Previous-generation GPT-5 pro reasoning model.\nExcels at complex reasoning and expert analysis with user-supplied API keys.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.2-pro"),
  },
  {
    id: "gpt-5.2-instant",
    name: "GPT-5.2 Instant",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description:
      "Ultra-fast variant of GPT-5.2 optimized for low-latency.\nIdeal for real-time conversations, quick answers, and high-throughput tasks.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.2-chat-latest"),
  },
  {
    id: "gpt-5.1",
    name: "GPT-5.1",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description: `OpenAI's latest reasoning model. \nDelivers state-of-the-art performance in logic, coding, and multi-step reasoning.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.1"),
  },
  {
    id: "gpt-5.1-instant",
    name: "GPT-5.1 Instant",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description:
      "Ultra-fast non-reasoning variant of GPT-5.1. \nOptimized for immediate responses and high-throughput applications.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5.1-chat-latest"),
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description: `OpenAI's flagship reasoning-first model. \nUnifies logic and multi-step problem-solving with enhanced coding and intelligence capabilities.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5"),
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini (Legacy)",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Legacy GPT-5 mini snapshot for compatibility.\nFor most new low-latency, high-volume workloads, start with GPT-5.4 Mini instead.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5-mini"),
  },
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano (Legacy)",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Legacy GPT-5 nano snapshot for compatibility.\nFor most new speed- and cost-sensitive workloads, start with GPT-5.4 Nano instead.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai.responses("gpt-5-nano"),
  },
  {
    id: "gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description: `OpenAI's new smaller 20B open-source model. \nAround o3-mini performance, with super fast inference by Groq.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [REASONING_FEATURE, TOOL_CALLING_FEATURE],
    api_sdk: gateway("openai/gpt-oss-20b"),
  },
  {
    id: "gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: "openai",
    displayProvider: "openai",
    premium: false,
    usesPremiumCredits: false,
    description: `OpenAI's new larger 120B open-source model. \nNearly as good as o4-mini, with super fast inference by Groq.`,
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [REASONING_FEATURE, TOOL_CALLING_FEATURE],
    api_sdk: gateway("openai/gpt-oss-120b"),
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description: `OpenAI's flagship multimodal model.\nProcesses text, images, and audio with fast, versatile performance.`,
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("gpt-4o"),
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Cost-efficient model with fast inference speed.\nPerfect for high-volume tasks and quick interactions.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("gpt-4o-mini"),
  },
  {
    id: "o4-mini",
    name: "o4 Mini",
    provider: "openai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Reasoning-focused model with 93% on AIME 2025.\nExcels at math, coding, and visual tasks at lower cost.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("o4-mini"),
  },
  {
    id: "o3",
    name: "o3",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    legacy: true,
    description:
      "Advanced reasoning model with 20% fewer errors than o1.\nExcels at programming, consulting, and creative tasks.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: false },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("o3"),
  },
  {
    id: "o3-pro",
    name: "o3 Pro",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Premium reasoning model with enhanced capabilities.\nDesigned for research-level and professional applications.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("o3-pro"),
  },
  {
    id: "gpt-image-1.5",
    name: "GPT Image 1.5",
    provider: "openai",
    premium: true,
    usesPremiumCredits: true,
    description:
      "OpenAI's latest image generation model with major improvements in realism and accuracy.\nFeatures high-fidelity photorealism, reliable text rendering, and precise style control.",
    apiKeyUsage: { allowUserKey: false, userKeyOnly: false },
    features: [IMAGE_GENERATION_FEATURE],
    api_sdk: openai.image("gpt-image-1.5"),
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    premium: true,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Enhanced GPT-4 with 55% on SWE-bench Verified.\nDelivers major improvements in coding and instruction following.",
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("gpt-4.1"),
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Efficient model balancing speed and capability.\nIdeal for everyday conversations and quick tasks.",
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("gpt-4.1-mini"),
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "Ultra-lightweight model with minimal latency.\nOptimized for resource-constrained environments.",
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("gpt-4.1-nano"),
  },
  {
    id: "gpt-4.5",
    name: "GPT-4.5",
    provider: "openai",
    premium: false,
    usesPremiumCredits: false,
    legacy: true,
    description:
      "General-purpose model with enhanced understanding.\nOffers better nuance, creativity, and aesthetic intuition.",
    apiKeyUsage: { allowUserKey: true, userKeyOnly: true },
    features: [
      FILE_UPLOAD_FEATURE,
      PDF_PROCESSING_FEATURE,
      REASONING_FEATURE_DISABLED,
      TOOL_CALLING_FEATURE,
    ],
    api_sdk: openai("gpt-4.5"),
  },
];
